#ENC[AES256_GCM,data:+m+F1hPgeTZ/ylWWpmxMVWP2oo/F3CxD+rpZtN5oGN9eaOX1rypt3tSDFpi989Zbfye6hf7+AdA5ObRHpwpRgjcYtXhq3aEhIfecKAEL1wqw2Oypl2d+S4JH0fm4TkEX7SMuQsVa8gZZlzMlYefHOQtg+LYZhtm2o7eTkUgXvpK8,iv:vkh3S2lXfRkXtz30kSlfYsTvYTt8qTHHOPYKQdVVWck=,tag:IMSLThnRcwPdI2Gu/0oaSg==,type:comment]
#ENC[AES256_GCM,data:eLAdSWlOuhvYA4Lf368Nl4X6GTIyEAQMkBuSxsC+g6RE1H2Fs0Jd4hmBdZ9vZRL5CwNdikue0lfIbcl1FQ==,iv:LEvV7gHUWRigzfUeK94U6Xt4TBxTN8hGd6NgTOF2HB4=,tag:TxOybI0d1lYbJsanThGpXA==,type:comment]
#ENC[AES256_GCM,data:ErqOWoBQWPeiMLh2ThtcR2nxP8LMQK4bD8wVGag6XzUO5U1Vsw==,iv:HDGgNu5nsrPLSLvkXMQroMdrokfKXbL9LNqY5sdJlcM=,tag:iXlIgtRIAH1/CpKJrYHImg==,type:comment]
#
#ENC[AES256_GCM,data:lUBf1C9J862kD1iRpfe4Y7AqUWMg07Wj4B9k6SFQdTfhaKttY0A0+jaC4p6Zeu/Chhc+ZI81srQSQwhf2GQhpH5pQritRf7e081vSE+Fv+7RaUxw/AUX0oSTdTrfNTP+5A==,iv:EbyxS8X+v9ig3+UFe3UQS1w8hsb3U+v2kwYAWG5++fc=,tag:183ETL6Aff7M0wLGIOeCsg==,type:comment]
#ENC[AES256_GCM,data:QIuOWQNUO4NpTr9IeXwP7Afdl768smgjcdjkhCjaucVVzpaJXf+meBt3QTwez0qrV8KnOKa9sm9/cgesiInPvzChyVh2Zrjpm3XkXNDEppfDKW/SN1wNO6MLRAD8AZcFq5lC8EoAv1E62tVzoYsfpjrH6CybR23/1aVVcUoxOfXkCA==,iv:SkyYMzW9l9pKuxj2Kc82VIQhWEIai/w3dRGvzHHwb+s=,tag:orKWS4XQBwVU/arP7ZJh5g==,type:comment]
#ENC[AES256_GCM,data:XV0dJb6jFbCND73aVKzOfQ5YYNTpccAGv7aNGGQnfw==,iv:hOJzuxmwSFdOMI9ewg6s3GVPPuJYHNkYTJBevPcteKQ=,tag:IfDTWQSqkYeL9DLC9X9PmQ==,type:comment]
secrets:
    DB_USER: ENC[AES256_GCM,data:K3s2Dw==,iv:oU0zvKUXFD5ErImKuWIV7LNsXihQo90qwLTpksTAHHw=,tag:eKO/0Eks1Z/CYMeJuaUMUQ==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:CD+/LMxvmaNeRtLF5obJxLweW4kS0IZt,iv:9SiTYiIz5e1k1sGGyrnMVS+lWsmBfkx47A+GyXa/mMU=,tag:uuSJBsuoyZTvuTfQHms2yw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGeFB3VzJDV0xsYjU3S1Jj
            aDkyV2c4T2hWaTkyQmNSemJZcnZwOU9RZTJrCitTN0MrTENna0FlL1pHQVBWQzAw
            M1NiZnVwb0NiY3dpK0hERFFUT1pubzQKLS0tIGR2SVBCUjJSRTZCa2lRc2tNbXM3
            Q3prbE1raHJ2MXdvc1ora0dJcnlJKzQKHjO7Q+prvkHK4m9wa3PWyM8ppMDKGZdZ
            jdyf2SMMsSq41ms6Z4V8pCzjlnBW3RLIzZ1sxWkMoTpaJ1IieRceYg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15kwvytt300z2p3tygq72hp0x7hr0dzc0w60czjt80t9nq5wadqxsruw0va
    lastmodified: "2026-09-13T12:11:39Z"
    mac: ENC[AES256_GCM,data:eUPwjBw3oePY2ySRiCRaQu7q71QtK54FIhYs61GNxIrDzszG/iyA+/yhBq+4ejG3dYa+1Xa59KP7Ep7Mw/PYDpL50RUkHqa0WQm+N9Msc71GY6J/1uEDh+LMw5PBsvB5k/DaAPZasPaPunid/aTgjN2s2ZbRpbqJDe848g2jIc4=,iv:FIRiGQTEgUaL175UeRtK1hrzc4KdozccITxmUHzrwZs=,tag:NCjjTk05UAq7XRRfEh3srQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
