#ENC[AES256_GCM,data:PWQJ+7YRL6yzkBoifa+gfgkD3INK6LZYdygSD8ZlC3t22ANPy7+BBcmmwRpP55sTQVRK42Spib7bVzo+Zzn/V/x8XEJFOe60e/pKr0Oiznut5G8jzM4b3adoJBFgBvVp0EAZdTO8aylV4JwddF9BUpgaD+/7oX+r49w4yQRfqs4=,iv:wxALTTF+fCYsahTZW2JvSuPFluhm2WCJKIOxH3wwLpE=,tag:J5Kq6IIvuka1AwE1Miktdw==,type:comment]
#ENC[AES256_GCM,data:5jWakPLYCrRyOJgcXpUitTsHk4c09R3+ENtohmTMl+pV2EZgX9RZ7U2LYNAlLDupiFI92wj885GiPFEQNWRJ9kLuSApcZkdyqyxCCzmjKts+LL0/Fnx3HXsM4Qxb9tU8L3adrxwrheBp328UaxWKHRVsJ7vnhahM,iv:6jNEGAkDE+9YNP4B1rMMSCSaHmvgaT7OKlgTGryqGc4=,tag:BNE3mD851lZKNGywJ6NryA==,type:comment]
#
#ENC[AES256_GCM,data:OuF2VtufDl/PzrV26PlUzLWOGuQRtCgdncw4xTQQDpJChaZtYq15ihpkdIBAJCuK00Su9dYr5sldRIxEBj6UfTKeEQ==,iv:E3hiz2Pi6Dvdbh6q9Y9CYC7xVWI2pU5LBK6LMKIWrsA=,tag:bCsUbtoCJW8dT8x0pkJXTg==,type:comment]
#ENC[AES256_GCM,data:auJDKQbaCosB5hIK16WaEM90oaQkIiJ9nTsnKES4JIJwLNxB3YZYGQ==,iv:EEqlCu94fq2hAvcN1ukTP99SdRDn5IRzJ4exqDc0Syg=,tag:QH9N38SlJ1aZhsihnld5uw==,type:comment]
#
#ENC[AES256_GCM,data:uEyubPwwGdVGei61eoXaYII19HopgBZtxb8muf8OnH/o+C3J6f4ttFMewfYLBWCaZq/dYYu86jm0DdWSep+goNf8up5jku9D8sd4kCMCLmorz+tfoGMZRlGsLA+kuwkFx51V76c0CKQ07D4nScyjDGYBJb5B,iv:2B5xN8ThqoZeBwFSHzT8DVnCgcx1j6X35YZIk2B6wX0=,tag:mmAlMLQTqpBG/IBppf7vag==,type:comment]
#ENC[AES256_GCM,data:1Ea4fmgO2oqCu/B9b7LZLV8gcUCji9yVzIlqNdepICWD4+6mModqrxjARyk47lyXWrzO5078i/yMYPYHCSWpnCa6knaygUWBmKPBnTLblIViyvMi5LK6GXjekXwtgDra4NgYYoj7WVmNxbdGjmCvavIcI5jPJZrqhe2geIG9+onzWKI64jZ4xy5gLCd3DVV/HPLk1lE=,iv:P8fCK+Abdh7CpVhmevAfNQZEfs4ip6iHdjSvrwCEdKQ=,tag:oK3bQwYiiSpOD1CvPsdrNQ==,type:comment]
secret:
    dbUser: ENC[AES256_GCM,data:xjJURg==,iv:ouiAJvm1tp34S9Fd0wWc2sr+eLExbpTtpx5fFNvMNHA=,tag:NVvdiCSvxKVOH+BS/PpS6Q==,type:str]
    dbPassword: ENC[AES256_GCM,data:/7YeBsPmBlR6Ot5sI3z33fdHsZ43zYz4,iv:0OJpbDgorV897LZnt5nv+UBuRjWzhnZZb3o6CWgS7vA=,tag:EWu370aA/Qx+MJ2dHY+SAA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpNVNnQU1QQ3ZzVGVsblBG
            NExtUkR1dTczS0lYYkFpSGNvZW56T1FNSHo0CjNLcWJsWlFwZnF5WkNVdmsrOVcw
            SmN1czhRQlAvUGR2cmoxQUVIRlZPbUkKLS0tIHU2N2RBOW01cWhOdDJTMnhyNVpF
            MUw0Ymh6UmJMc0l5VlViL25PSkdKdTgKcP0e4sxYHGbScQYUgy5N78nAPjJXaTTK
            fLfpqCDftjhVVpefBJWCEq8U9GdboIR5Y/wWwRh95fvRCQ/pOxUrWw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15kwvytt300z2p3tygq72hp0x7hr0dzc0w60czjt80t9nq5wadqxsruw0va
    lastmodified: "2026-09-13T12:11:39Z"
    mac: ENC[AES256_GCM,data:or8Jm2+HI+Ba1znhKehuMU50lMHzMW0Sz9iGkRq3+RRsBPFEzezggEowy4vZtC9gCgG7MjHdl38t9Rpvfwa8OtZxHxlEGj3yWD4X/jD662f4viYlX/K2m0AIRKv1t9rQDkihpp0uYLw4yifS6CXOUvp2wMRoyhL95zhgTS9YrL8=,iv:D9X4gsWCKPLtcAXqLgEVluQDZC1KuhW5bVNCIVwQTS4=,tag:SMnk75Rn1N5IYwM5PYeanw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
